# Generated by Django 4.2.3 on 2023-07-20 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Quiz_App", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quiz",
            name="creator",
        ),
        migrations.AddField(
            model_name="quiz",
            name="created_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="Quiz_App.user",
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="date_created",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="difficulty",
            field=models.CharField(
                choices=[("Easy", "Easy"), ("Medium", "Medium"), ("Hard", "Hard")],
                max_length=10,
            ),
        ),
    ]
