# Generated by Django 4.2.3 on 2023-07-20 02:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("Quiz_App", "0003_alter_quiz_created_by_alter_quizresult_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Quiz_App.user"
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="date_created",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="quizresult",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Quiz_App.user"
            ),
        ),
    ]
