# Generated by Django 4.2.3 on 2023-07-21 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Quiz_App", "0008_alter_quizresult_quiz"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizresult",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quiz_results",
                to="Quiz_App.quiz",
            ),
        ),
    ]
